### ISSUE TITLE
Reduce the context sent for translation

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/python-translators#9]
The context we are sending to google is too large: we are sending more than a sentence. e.g.

 -- left context:
Justitieminister Koen Geens (CD&V) werkt aan een wetsontwerp dat burgerinfiltranten mogelijk maakt in de strijd tegen
 -- right context:  en georganiseerde misdaad. Dat zegt hij woensdag in Knack, nadat Brussels procureur-generaal Johan Delmulle daar vorig najaar een lans voor had gebroken. Daar
naast werkt Geens ook aan een regeling rond spijtoptanten. Een akkoord binnen de meerderheid is er nog niet.

In principle the reader people should make sure that they keep the context short, but we can't rely on that. So the `translators` service should also limit the context to at least the sentence, if not even more drastic heuristics.

**Comment by thejager** [comment]
Right, in this case you could just remove everything after the first occurrence of a period or even a period followed by a space (or whitespace in general). I'm just not sure if this would work for all languages and cases. It's hard to figure this out.

I have an idea for this. Give me a bit, I'll write some things down :)

**Comment by thejager** [comment]
I think we both agree that we won't find a general approach that works for all languages. Therefore, I think we need a way to deal with issues in specific languages or maybe groups of languages like the Germanic languages.

What if we do this:

Every translator has 0 or more pre-processors attached. All pre-processors are ran in order. Every pre-processor receives the before_context, after_context (and maybe query?). Each pre-processor can modify the context as he pleases. After a pre-processor has done its job it passes it on to the next pre-processor.

An example of a pre-processor would be one that restricts the context to one sentence where each sentence is separated by periods followed by whitespace. This works (assuming well-formed sentences) for translations from Dutch to all other languages. The example you gave would be transformed to:

-- left context:
Justitieminister Koen Geens (CD&V) werkt aan een wetsontwerp dat burgerinfiltranten mogelijk maakt in de strijd tegen
-- right context: en georganiseerde misdaad.

However, this would not work for sentences written in Hindi. Apparently they separate their sentences by vertical bars: "।". We could attach a different pre-processor for this translator.

One more example: let's say you want to translate "capital city" in the English sentence "It is sunny and Amsterdam is the capital city of the Netherlands but Groningen is more awesome". This is pretty much a conjunction of three sentences and you can strip out the first and third sentence by splitting on words like "but", "and" and "or" resulting in:

"Amsterdam is the capital city of the Netherlands".

This cuts the number of characters by ~51%.

I think this would be a good way to deal with language specific pre-processing of transformations.

A few things that I think we need to change for this: the source and target languages should be specified per translator instance instead of per method call.

```
g = GoogleTranslator(source_language='nl', target_language='en', key='<some valid API key')
g.addPreProcessor(RemoveUnneededSentences(separator='. '))
g.addPreProcessor(FilterOnConjunctions())
print(g.translate(before_context='De directeur', query='treedt af', after_context=''))
```

Also, I think we can extend this to post-processing as well. Right now, in the GoogleTranslator I have a hardcoded rule that says that if the query doesn't have a trailing punctuation then I remove trailing punctuation from the translation. We could move these kind of rules to a list of postprocessors.

A detail: setting up these translators and their associated pre- and postprocessors could be centralised in a Factory. Something like this:

```python
gt = GoogleTranslatorFactory.make(source_language='nl', target_language='en', key='<valid google key>')
```

```python
GERMANIC_LANGUAGES = ['nl', 'en', 'de' ....]
class GoogleTranslatorFactory(object):
	def make(source_language, target_language, key):
		gt = GoogleTranslator(key=key)

		if source_language in germanic_languages:
			# add germanic specific pre- and post-processors
```

Let me know what you think!

**Comment by mircealungu** [comment]
Hi Johan,
